export const START_LOADING = 'START_LOADING';
export const END_LOADING = 'END_LOADING';

export const SIGN_UP_USER_REQUEST = 'SIGN_UP_USER_REQUEST';
export const SIGN_UP_USER_SUCCESS = 'SIGN_UP_USER_SUCCESS';
export const SIGN_UP_USER_ERROR = 'SIGN_UP_USER_ERROR';

export const SIGN_IN_USER_REQUEST = 'SIGN_IN_USER_REQUEST';
export const SIGN_IN_USER_SUCCESS = 'SIGN_IN_USER_SUCCESS';
export const SIGN_IN_USER_ERROR = 'SIGN_IN_USER_ERROR';

export const ADD_USER_SCHEDULE_REQUEST = 'ADD_USER_SCHEDULE_REQUEST';
export const ADD_USER_SCHEDULE_SUCCESS = 'ADD_USER_SCHEDULE_SUCCESS';
export const ADD_USER_SCHEDULE_ERROR = 'ADD_USER_SCHEDULE_ERROR';

export const RESET_PWD_REQUEST = 'RESET_PWD_REQUEST';
export const RESET_PWD_SUCCESS = 'RESET_PWD_SUCCESS';
export const RESET_PWD_ERROR = 'RESET_PWD_ERROR';

export const SEND_EMAIL_REQUEST = 'SEND_EMAIL_REQUEST';
export const SEND_EMAIL_SUCCESS = 'SEND_EMAIL_SUCCESS';
export const SEND_EMAIL_ERROR = 'SEND_EMAIL_ERROR';

export const RESET_PASSWORD_REQUEST = 'RESET_PASSWORD_REQUEST';
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_ERROR = 'RESET_PASSWORD_ERROR';

export const NEW_COACH_REQUEST = 'NEW_COACH_REQUEST';
export const NEW_COACH_SUCCESS = 'NEW_COACH_SUCCESS';
export const NEW_COACH_ERROR = 'NEW_COACH_ERROR';

export const ADD_CONTENT_REQUEST = 'ADD_CONTENT_REQUEST';
export const ADD_CONTENT_SUCCESS = 'ADD_CONTENT_SUCCESS';
export const ADD_CONTENT_ERROR = 'ADD_CONTENT_ERROR';

export const CLEAR_STORE = 'CLEAR_STORE';
export const NAME_VALIDATE_ERROR = 'NAME_VALIDATE_ERROR';

export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_ERROR = 'LOGOUT_ERROR';

export const GET_USERS_REQUEST = 'GET_USERS_REQUEST';
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';
export const GET_USERS_FAIL = 'GET_USERS_FAIL';

export const GET_COACHES_REQUEST = 'GET_COACHES_REQUEST';
export const GET_COACHES_SUCCESS = 'GET_COACHES_SUCCESS';
export const GET_COACHES_FAIL = 'GET_COACHES_FAIL';

export const APPROVE_APPLICATION_REQUEST = 'APPROVE_APPLICATION_REQUEST';
export const APPROVE_APPLICATION_SUCCESS = 'APPROVE_APPLICATION_SUCCESS';
export const APPROVE_APPLICATION_FAIL = 'APPROVE_APPLICATION_FAIL';
